extends:
- eslint:recommended
- plugin:import/recommended
- plugin:mozilla/recommended
- plugin:react/recommended

settings:
  react:
    version: "16.4.2"
    
env:
  browser: true
  es6: true
  jquery: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 6

root: true

rules:
  # no-console: "warn"
  no-console: off
  arrow-parens: off
  comma-dangle: off
  function-paren-newline: off
  guard-for-in: off
  no-trailing-spaces: off
  import/no-named-as-default: off
  import/prefer-default-export: off
  linebreak-style: off
  no-multi-assign: off
  no-plusplus: off
  no-restricted-syntax: off
  no-use-before-define: off
  object-curly-newline: off
  react/prop-types: off
  eol-last: off

overrides:
  -
    files:
      - 'client/src/**/*.js'
    globals:
      module: true
      process: true
      require: true
  -
    files:
      - 'index.js'
      - 'bin/**/*.js'
      - 'server/**/*.js'
    env:
      node: true
  -
    files:
      - 'webpack.*.js'
    rules:
      import/unambiguous: off
    env:
      node: true